#docker-compose -f docker-compose.local.yml up
#docker-compose -f docker-compose.local.yml build
#docker-compose -f docker-compose.local.yml down -v --remove-orphans
version: '3.7'

services:
    server:
        volumes:
            - type: bind
              source: ./src
              target: /app/src
            - /app/node_modules
        env_file:
            - '.env'
        depends_on:
            - mariadb
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: atemplate-dev
        networks:
            - backend
        restart: always
        ports:
            - 9000:9000

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        volumes:
            - type: bind
              source: ./db
              target: /var/lib/mysql
        env_file:
            - '.env'
        ports:
            - 3306:3306
        networks:
            - backend

networks:
    backend:
