apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atemplate.name" . }}-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "atemplate.labels" . | nindent 4 }}
data:
  HOST: http{{ if $.Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.host }}
  NODE_ENV: {{ .Values.config.environment }}