apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atemplate.name" . }}-secret
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "atemplate.labels" . | nindent 4 }}
type: Opaque
data:
  EXAMPLE: eHh4eA==