export const httpStatusCodes = {
    ACCEPTED: 202,
    BAD_GATEWAY: 502,
    BAD_REQUEST: 400,
    CONTINUE: 100,
    CREATED: 201,
    FORBIDDEN: 403,
    GATEWAY_TIME_OUT: 504,
    INTERNAL_SERVER_ERROR: 500,
    NOT_FOUND: 404,
    NOT_IMPLEMENTED: 501,
    NO_CONTENT: 204,
    OK: 200,
    REQUEST_TIMEOUT: 408,
    SERVICE_UNAVAILABLE: 503,
    UNAUTHORIZED: 401,
    UNPROCESSABLE_ENTITY: 422,
};

export const httpStatusMessages = {
    ACCEPTED: 'ACCEPTED',
    BAD_GATEWAY: 'BAD_GATEWAY',
    BAD_REQUEST: 'BAD_REQUEST',
    CONTINUE: 'CONTINUE',
    CREATED: 'CREATED',
    FORBIDDEN: 'FORBIDDEN',
    GATEWAY_TIME_OUT: 'GATEWAY_TIMEOUT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    NO_CONTENT: 'NO_CONTENT',
    OK: 'OK',
    REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
};

export const httpResponseStatus = {
    ERROR: 'error',
    FAILED: 'failed',
    SUCCESS: 'success',
};
